# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-19 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam', '0002_auto_20181019_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='belt_exam.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_jobs', to='belt_exam.User'),
        ),
    ]
