# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-18 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteUser',
            new_name='User',
        ),
    ]
